name: Update README.md cards

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@e856fc8de9d7729b463c468911e232cfbdc3d55e #v2.0.2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_title=true
          path: cards/stats.svg
          token: ${{ secrets.STATS_TOKEN }}
          core_version: "2.1.5"
          fail_on_error: "true"

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add cards/*.svg
          git commit -m "Update README.md cards" || exit 0
          git push
